export const ON_GLOBAL_REQUEST_PROGRESS = Symbol('ON_GLOBAL_REQUEST_PROGRESS')
export const ON_GLOBAL_RESPONSE_PROGRESS = Symbol('ON_GLOBAL_RESPONSE_PROGRESS')
export const ABORT_CONTROLLER = Symbol('ABORT_CONTROLLER')
